name-template: "v`$RESOLVED_VERSION"
tag-template: "`$RESOLVED_VERSION"

categories:
  - title: "🚀 Features"
    labels: [enhancement, feature]
  - title: "🐛 Fixes"
    labels: [bug, fix]
  - title: "🧰 Maintenance"
    labels: [chore, refactor]
  - title: "📚 Docs"
    labels: [docs]
  - title: "🧪 CI"
    labels: [ci]
  - title: "🔐 Security"
    labels: [security]

change-template: "- `$TITLE (#`$NUMBER) by @`$AUTHOR"
change-title-escapes: "<>&"

version-resolver:
  major:
    labels: [major]
  minor:
    labels: [minor, enhancement, feature]
  patch:
    labels: [patch, bug, fix, chore, docs, ci, security]
  default: patch

exclude-labels:
  - skip-changelog

template: |
  ## Changes
  `$CHANGES

  ---
  _This release was drafted automatically. Use labels to sort entries and add `skip-changelog` to exclude PRs._
