line-length = 100
indent-width = 4
target-version = "py312"

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
docstring-code-format = true

[lint]
select = ["E", "F", "I", "UP", "B"]
ignore = ["E203"]  # Black-compatible slicing

[lint.isort]
known-first-party = ["tools.ppt_builder"]
combine-as-imports = true
