from typing import Any
# deck_slides.py
from slides import *  # re-export everything for older scripts/editors


def add_full_slide_picture(slide: Any, prs: Any, image_path: str) -> None: ...
def add_title_box(slide: Any, text: str, *, left_in: float, top_in: float, width_in: float, height_in: float,
                  font_size_pt: int = ..., bold: bool = ..., color: str = ..., align: Any = ...) -> None: ...
def add_text_box(slide: Any, text: str, *, left_in: float, top_in: float, width_in: float, height_in: float,
                 font_size_pt: int = ..., bold: bool = ..., color: str = ..., align: Any = ...) -> None: ...
def add_cover_slide(prs: Any, assets: dict, cover_title: str, cover_dates: str, logo1_path: str | None, logo2_path: str | None) -> None: ...
def add_agenda_slide(prs: Any, assets: dict, agenda_lines: list[str] | None = ...) -> None: ...
def add_separator_slide(prs: Any, assets: dict, title: str) -> None: ...
def add_conclusion_slide(prs: Any, assets: dict, links: list[tuple[str,str]]) -> None: ...
