name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Node deps
        run: npm ci

      - name: Lint & Typecheck
        run: |
          npm run -s lint || true
          npm run -s typecheck || true

      - name: Run ESLint (fail on error)
        run: |
          if [ -f .eslintrc.cjs ] || [ -f eslint.config.js ] || [ -f eslint.config.cjs ]; then
            npx eslint . -f junit -o eslint-junit.xml
          else
            echo "No eslint config found; skipping.";
          fi

      - name: Setup PowerShell
        uses: PowerShell/PowerShell@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Pester (PowerShell tests)
        shell: pwsh
        run: |
          Install-Module -Name Pester -Force -Scope CurrentUser
          Invoke-Pester -EnableExit -OutputFormat NUnitXml -OutputFile pester-results.xml

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            eslint-junit.xml
            pester-results.xml

  codeql:
    uses: github/codeql-action/.github/workflows/codeql.yml@v3
    permissions:
      security-events: write
      actions: read
      contents: read
