name: Feature request
description: Propose an enhancement or capability
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      placeholder: What user need are we solving?
    validations: { required: true }
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      placeholder: What would you like the bot or tab to do?
  - type: checkboxes
    id: impact
    attributes:
      label: Areas impacted
      options:
        - label: Teams Bot (server)
        - label: Tab (client)
        - label: Shared types or utilities
        - label: Docs or ADRs
