name: Collect and Review Files with OpenAI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # daily at midnight UTC

jobs:
  review:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Collect files for review
      run: |
        mkdir review_package
        find ./src ./docs -type f \( -name "*.py" -o -name "*.md" \) -exec cp --parents {} review_package/ \;

    - name: Upload Artifact
      uses: actions/upload-artifact@<commit-sha>
      # Example:
      # uses: actions/upload-artifact@4d1fcfd1ca64e052d7b2321120c81c2f38806b50
      with:
        name: my-artifact-${{ matrix.runs-on }}
        path: file-${{ matrix.runs-on }}.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip requests

    - name: Run review script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python scripts/send_openai.py review_package/
